{% set name = "openvscode-server" %}
{% set version = "1.65.0" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/gitpod-io/openvscode-server/releases/download/openvscode-server-v{{ version }}/openvscode-server-v{{ version }}-linux-x64.tar.gz  # [linux64]
  sha256: a5ede74c7bb7d73f8c100b8637a628a210f18cb69cd1fccc64b8a5afffc801a5
  folder: openvscode-server

build:
  number: 0
  skip: true  # [not linux64]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - nodejs 14.*
  run:
    - nodejs 14.*

test:
  commands:
    - openvscode-server --help

about:
  home: https://github.com/gitpod-io/openvscode-server
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
    - ThirdPartyNotices.txt
  summary: Run upstream VS Code on a remote machine with access through a modern web browser from any device, anywhere.

extra:
  recipe-maintainers:
    - xhochy
    - jtilly
    - janjagusch
